### ISSUE TITLE
无法获取到应用的图片，有没有办法支持呢

### ISSUE THREAD

**Issue by didoee** [Xutaotaotao/get-installed-apps#7]
DisplayIcon这个字段无法正常显示图标

**Comment by Xutaotaotao** [comment]
按道理应该也行，就是读注册表的值，你可以尝试提个PR，哈哈哈哈

**Comment by didoee** [comment]
> 按道理应该也行，就是读注册表的值，你可以尝试提个PR，哈哈哈哈

简直倒反天罡，哈哈哈😄
有些应用可以，有些不可以，不知道什么原因，可以加vx沟通一下吗

**Comment by Xutaotaotao** [comment]
> > 按道理应该也行，就是读注册表的值，你可以尝试提个PR，哈哈哈哈
> 
> 简直倒反天罡，哈哈哈😄 有些应用可以，有些不可以，不知道什么原因，可以加vx沟通一下吗

github 主页有我微信，可添加好友，备注就行啦
