### ISSUE TITLE
如何获取启动路径

### ISSUE THREAD

**Issue by GeekKekeQiu** [Xutaotaotao/get-installed-apps#9]
`windows`下如何拿到启动app的可执行文件路径，现在只有`InstallLocation`安装路径，如果要启动还得知道可执行文件的名字，和`appName`不一样

**Comment by Xutaotaotao** [comment]
这个其实不是很好获取，注册表一般也不会提供，而且启动路径是可以随意控制的，就跟快捷方式也可以变化的一样，要么就是遍历安装路径下的exe 去除掉卸载程序，挨个启动，或者你可以记录用户的进程把它存起来，进程路径是最准的。如果还有问题可以GitHub主页加我微信咨询

**Comment by GeekKekeQiu** [comment]
好的，谢谢，我们换了个思路做了，本来想用[open](https://www.npmjs.com/package/open)帮助打开app的~

**Comment by Happier-X** [comment]
> 好的，谢谢，我们换了个思路做了，本来想用[open](https://www.npmjs.com/package/open)帮助打开app的~

您好，请问您是如何获取启动路径然后打开app的
